services:
  fastapi:
    build: ./core  # Build from the Dockerfile in the 'app' folder
    ports:
      - "8000:8000"
    volumes:
      - ./core:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "443:443"  # Expose HTTPS
      - "80:80"    # Expose HTTP
    depends_on:
      - fastapi
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis-data:/data
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=u
      - MONGO_INITDB_ROOT_PASSWORD=p
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
  mongo-data:
